config/routes.rb
Weblog::Application.routes.draw do
  root :to => "pages#home"
  
  get 'home' => "pages#home"
  get 'posts' => "pages#posts"
  get 'view' => "pages#view"
  get 'about' => "pages#about"
  get 'contact' => "pages#contact"
  
  get 'admin' => "admin#index"
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  resources :users
  resources :blogs

  post 'contact', :to => "blogs#send_contact"

  
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user, :inverse_of => :blogs
  
  validates :title, :presence => true, :uniqueness => true
  validates :content, :presence => true
  validates_presence_of :user
  attr_accessible :title, :content
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  after_destroy :ensure_an_admin_remains
  has_many :blogs, :inverse_of => :user
  
  validates :name, :presence => true, :uniqueness => true
  
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password
  
  validate :password_must_be_present
  
  def User.authenticate(name, password)
   if user = find_by_name(name)
     if user.hashed_password == encrypt_password(password, user.salt)
       user
     end
   end
  end
  
  def User.encrypt_password(password, salt)
   Digest::SHA2.hexdigest(password + "wibble" + salt)
  end
   
  #password is a virtual attribute
  def password=(password)
   @password = password
   
   if password.present?
     generate_salt
     self.hashed_password = self.class.encrypt_password(password, salt)
   end
  end
   
  private
    
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end
  
    def password_must_be_present
      errors.add(:password, "Missing Password") unless hashed_password.present?
    end
    
    def generate_salt
      self.salt = self.object_id.to_s + rand.to_s
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authorize
  
  private

    def current_user
      @current_user = User.find_by_id(session[:user_id])
    end
  
  protected
    def authorize
      unless User.find_by_id(session[:user_id])
        redirect_to login_url, :notice => "Please log in."
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authorize
  skip_before_filter :authorize, :only => [:show]
  
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = current_user.blogs

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = current_user.blogs.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = current_user.blogs.build(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = current_user.blogs.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = current_user.blogs.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :ok }
    end
  end
  
  def send_contact
    if params[:nametext] == "" or params[:emailtext] == "" or params[:messagetext] == ""
      flash[:error] = "Please Fill in all required Information(*)"
      render :action => 'contact'
    elsif (params[:emailtext] =~ /^[A-Z0-9_\.%\+\-\']+@(?:[A-Z0-9\-]+\.)+(?:[A-Z]{2,4}|museum|travel)$/i) == nil
      flash[:error] = "Please enter a valid email address"
      render :action => 'contact'
    else
      ContactMailer.inquiry(params).deliver
      flash[:notice] = "Email was successfully sent"
      redirect_to '/'
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authorize  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize
  def new
  end

  def create
    if user = User.authenticate(params[:name], params[:password])
      session[:user_id] = user.id
      redirect_to admin_url
    else
      redirect_to login_url, :alert => "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/home', :notice => "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(users_url, notice: "#{@user.name} was successfully created.") }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_url, notice: "#{@user.name} was successfully updated.") }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    begin
      @user.destroy
      flash[:notice] = "User #{@user.name} deleted."
    rescue Exception => e
      flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div id="adminouter">
	
	<h1> Welcome! </h1>
	<div id="admininner">
	<h2>What would you like to do?</h2>
			<ul>
				<li><%=link_to "See My Posts", blogs_path%></li>
				<li><%=link_to "New Post", new_blog_path%></li>
				<li><%=link_to 'Logout', logout_path, :method => :delete%></li>
			</ul>
	</div>
</div>

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="titlefield">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="contentfield">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div id="editpost">
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div id="bindex">
<%= link_to 'New Post', new_blog_path, {:style => "float: right"} %>

<h1><%= @current_user.name%>'s Blogs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= truncate(blog.content, :length => 210) %></td>
    <td><%= link_to 'Show', blog %></td>
    <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    <td><%= link_to 'Destroy', blog, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

</div>

app/views/blogs/new.html.erb
<div id="newpost">
	
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/posts.html.erb
<div id="posts">
	<h1> All Posts </h1>
	<% @user = User.all%>
	<% @user.each do |user| %>
		<div class="<%=user.name%>">
		<h2> Posts by <%=user.name%></h2>
		<% if user.blogs.empty?%>
			<p>There are no posts!</p>
		<%else%>
			<table>
  				<tr>
    				<th>Title</th>
  				</tr>
				<% user.blogs.each do |b| %>
  				<tr>
    				<td><%= link_to b.title, :action => 'show', :user_id => user, :id => b %></td>
  				</tr>
				<%end%>
			</table>
		<%end%>
		</div>
	<%end%>	
</div>

app/views/blogs/show.html.erb
<div id="showpost">
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @blog.title %>
</p>

<p>
  <b>Content:</b>
  <%= @blog.content %>
</p>
<% if @current_user != nil%>
	<%= link_to 'Edit', edit_blog_path(@blog) %> |
	<%= link_to 'Back', blogs_path %>
<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Level Ground</title>
  <%=stylesheet_link_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id='navbar'>
		<ul>
			<% current_user = User.find_by_id(session[:user_id])%>	
			<% if current_user != nil %>
				<li><%=link_to "Admin Home", admin_path%></li>
				<li><%=link_to "My Posts", blogs_path %></li>
				<li><%=link_to "New Post", new_blog_path %></li>
				<li><%= link_to 'Logout', logout_path, :method => :delete, :class => "logoutlink" %></li>
			<% else %>
				<li><a href="/">Home</a> </li>
				<li><a href="/posts">Posts</a> </li>
				<li><a href="/about">About Us</a> </li>
				<li><a href="/contact">Contact Us</a> </li>
				<li><%= link_to 'Login', login_path, :class => "loginlink" %></li>
			<%end%>
		</ul>
    </div>

	<div id="content">
	  <div id="headtext">
			<h1> Level Ground </h1>
				<p>"Teach me to do Your will, for You are my God; let Your good Spirit lead me on level ground." Psalm 143:10</p>
			<p> Welcome to Level Ground, a blog about anything and everything. Well, almost. This blog will encompass the random musings of a young Christian couple. You will find that the blogs posted here will be from the thoughts of Jordan and Laura Bracy, thoughts which will hopefully cause you to think about what you believe, why you believe it, and how it impacts and affects your life. To find out more about us and about this blog please visit the "About Us" section. </p>
	  </div>
	
	  <%= yield %>
	</div>
	<div id="spacer"></div>
	
	<div id="footer">
		<ul>
			<li id="siteinfo">Designed and Developed by: Jordan Bracy</li>
		</ul>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<div id="about">
  <h1> About Us </h1>
  <div id="ainfo"><!-- We've been married since July 9, 2011 and desire to serve God on the mission field. Laura wants to translate the Bible, making God's Word available to anyone and everyone and Jordan wants to disciple people, helping them to make the most of their lives by glorifying God.

  <div id="Jordan">
    <h2>About Jordan</h2>
	<p></p>
  </div>
  
  <div id="Laura">
	<h2>About Laura</h2>
	<p></p>-->
	Coming Soon!
  </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div id="contact">
	<h1>Contact Us</h1>
	<div id="contactinner">
		Coming Soon!
		<div id="contactform">
			<%#= form_tag contact_url do %>
				<%#= text_field_tag 'name', "Name(required):", {:onfocus => "this.value=''", :name => "nametext", :class => "nametext"}%>
				<%#= email_field_tag 'email', "Email(required):", {:onfocus => "this.value=''", :name => "emailtext", :class => "emailtext"}%>
				<%#= text_area_tag 'message', "Message(required):", {:onfocus => "this.value=''", :name => "messagetext", :class => "messagetext"}%>
				<%#= submit_tag "Send", {:class => "submit"}%>
			<%#end%>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<div id="home">
	<h1> Welcome! </h1>
	
	<div class="Jordan">
		<% user = User.find_by_name('Jordan')%>
		<h2>Jordan's Blog</h2>
		<% if  user.blogs.last != nil %>
			<%blog=user.blogs.last%>
			<table>
				<tr>
					<td class="title">
						<strong><%=link_to user.blogs.last.title, blog_path(blog) %></strong>
					</td>
				</tr>
				<tr>
					<td class="blogtent"> 
						<%= user.blogs.last.content %>
					</td>
				</tr>
			</table>
		<%else%>
			<p>There are no posts</p>
		<%end%>
	</div>
	
	<div class="Laura">
		<%user = User.find_by_name('Laura')%>
		<h2>Laura's Blog</h2>
		<% if  user.blogs.last != nil %>
			<%blog=user.blogs.last%>
			<table>
				<tr>
					<td class="title">
						<strong><%= link_to user.blogs.last.title, blog_path(blog) %></strong>
					</td>
				</tr>
				<tr>
					<td class="blogtent"> 
						<%= user.blogs.last.content %>
					</td>
				</tr>
			</table>
		<%else%>
			<p>There are no posts</p>
		<%end%>
	</div>
</div>

app/views/pages/posts.html.erb
<div id="posts">
	<h1> All Posts </h1>
	<% @user = User.all%>
	<% @user.each do |user| %>
		<div class="<%=user.name%>">
		<h2> Posts by <%=user.name%></h2>
		<% if user.blogs.empty?%>
			<p>There are no posts!</p>
		<%else%>
			<table>
  				<tr>
    				<th>Title</th>
  				</tr>
				<% user.blogs.each do |b| %>
  				<tr>
						
    				<td><%= link_to b.title, blog_path(b)%></td>
  				</tr>
				<%end%>	
			</table>
		<%end%>
		</div>
	<%end%>	
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend> Enter User Details</legend>

  <div>
	<%= f.label :name %>:
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password, 'Password' %>:
    <%= f.text_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation, 'Confirm' %>:
    <%= f.text_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit %>
  </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
	<%if notice %>
		<p id="notice"><%= notice %></p>
	<%end%>

<table>
  <tr>
    <th> name</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b> name:</b>
  <%= @user. name %>
</p>

<p>
  <b>Hashed password:</b>
  <%= @user.hashed_password %>
</p>

<p>
  <b>Salt:</b>
  <%= @user.salt %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>